#include "bsp_push_rog.h"
#include "main.h"

void left_push_rog_off(void)
{
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN1_GPIO, LEFT_PUSH_ROG_IN1_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN2_GPIO, LEFT_PUSH_ROG_IN2_PIN, GPIO_PIN_RESET);
}

void elongate_left_push_rog(void)
{
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN1_GPIO, LEFT_PUSH_ROG_IN1_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN2_GPIO, LEFT_PUSH_ROG_IN2_PIN, GPIO_PIN_SET);
}

void shorten_left_push_rog(void)
{
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN1_GPIO, LEFT_PUSH_ROG_IN1_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(LEFT_PUSH_ROG_IN2_GPIO, LEFT_PUSH_ROG_IN2_PIN, GPIO_PIN_RESET);
}

void right_push_rog_off(void)
{
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN3_GPIO, RIGHT_PUSH_ROG_IN3_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN4_GPIO, RIGHT_PUSH_ROG_IN4_PIN, GPIO_PIN_RESET);
}

void elongate_right_push_rog(void)
{
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN3_GPIO, RIGHT_PUSH_ROG_IN3_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN4_GPIO, RIGHT_PUSH_ROG_IN4_PIN, GPIO_PIN_RESET);
}

void shorten_right_push_rog(void)
{
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN3_GPIO, RIGHT_PUSH_ROG_IN3_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(RIGHT_PUSH_ROG_IN4_GPIO, RIGHT_PUSH_ROG_IN4_PIN, GPIO_PIN_SET);
}
